#!/usr/bin/bash
#
# installiert die in diesem Verzeichnis vorhandenen Dateien
# fuer den lokalen Benutzer
#

SHAREDIRKDE5=~/.local/share//kservices5
SHAREDIRNEMO=~/.local/share/nemo

######################### KDE 5 / Plasma / Dolphin
# Wenn entsprechendes Ziel-Verzeichnisse noch nicht existieren, dann lege es an
[ -d "${SHAREDIRKDE5}"/ServiceMenus ] || mkdir -p "${SHAREDIRKDE5}"/ServiceMenus 

# kopiere die Dateien in die entsprechenden Verzeichnisse
cp -t "${SHAREDIRKDE5}"/ServiceMenus/ *.desktop

# in Dolphn als Service anmelden
kbuildsycoca4
kbuildsycoca5

######################### Cinnamon / Nemo
# Wenn entsprechende Ziel-Verzeichnisse noch nicht existieren, dann lege sie an
[ -d "${SHAREDIRNEMO}"/actions ] || mkdir -p "${SHAREDIRNEMO}"/actions 
[ -d "${SHAREDIRNEMO}"/scripts ] || mkdir -p "${SHAREDIRNEMO}"/scripts 

# kopiere die Dateien in die entsprechenden Verzeichnisse
cp -t "${SHAREDIRNEMO}"/actions/ *.nemo_action 
cp -t "${SHAREDIRNEMO}"/scripts/ *.nemo_script
chmod u+x "${SHAREDIRNEMO}"/scripts *.nemo_script
# nemo neu starten
nemo -q
nemo

######################## Arbeitsscript in 
# Wenn entsprechendes Ziel-Verzeichnisse noch nicht existieren, dann lege es an
[ -d ~/bin ] || mkdir ~/bin

# kopiere die Dateien in dieses Verzeichnis
cp -t ~/bin/ ksm_*


# Datei ausfuehrbar machen
chmod u+x ~/bin/ksm_*

