#!/usr/bin/bash
#
# installiert die in diesem Verzeichnis vorhandenen Dateien
# fuer den lokalen Benutzer
#
set -x
######################### KDE 5/6 / Plasma 5/6 / Dolphin
# Wenn entsprechendes Ziel-Verzeichnisse noch nicht existieren, dann lege es an
[ -d ~/.local/share/kservices5/ServiceMenus ] || mkdir -p ~/.local/share/kservices5/ServiceMenus 
[ -d ~/.local/share/kio/servicemenus ] || mkdir -p ~/.local/share/kio/servicemenus 

# kopiere die Dateien in die entsprechenden Verzeichnisse KDE Plasma 5/6
cp -t ~/.local/share/kservices5/ServiceMenus/ *.desktop
cp -t ~/.local/share/kio/servicemenus/ *.desktop

# in Dolphn als Service anmelden
# kbuildsycoca4
kbuildsycoca5
kbuildsycoca6

######################### Cinnamon / Nemo
# Wenn entsprechende Ziel-Verzeichnisse noch nicht existieren, dann lege sie an
[ -d ~/.local/share/nemo/actions ] || mkdir -p ~/.local/share/nemo/actions 

# kopiere die Dateien in die entsprechenden Verzeichnisse
cp -t ~/.local/share/nemo/actions/ *.nemo_action
# Nemo beenden
nemo -q

######################## Arbeitsscript in 
# Wenn entsprechendes Ziel-Verzeichnisse noch nicht existieren, dann lege es an
[ -d ~/bin ] || mkdir ~/bin

# kopiere die Dateien in dieses Verzeichnis
cp -t ~/bin/ ksm_* 
cp -t ~/bin/ nemo_*


# Datei ausfuehrbar machen
chmod u+x ~/bin/ksm_* 
chmod u+x ~/bin/nemo_*

